spring:
  application:
    name: DemoSpringMVC
  datasource:
    url: jdbc:postgresql://localhost:5433/demospringmvc
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080